#!/usr/bin/env python3
"""Generate a tiny 2-bit antialiased digit atlas for the ESP8266 clock."""

from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
FONT_PATH = ROOT / "assets/fonts/RobotoCondensed-VariableFont_wght.ttf"
OUT_PATH = ROOT / "src/features/clock/RobotoCondensedDigits.h"
CHARS = "0123456789:"
HEIGHT = 58
FONT_SIZE = 58

font = ImageFont.truetype(str(FONT_PATH), FONT_SIZE)
try:
    font.set_variation_by_axes([600])
except (AttributeError, OSError):
    pass

glyphs: list[tuple[str, int, bytes]] = []
for char in CHARS:
    bbox = font.getbbox(char, anchor="lt")
    visible_w = bbox[2] - bbox[0]
    width = (visible_w + 4) if char != ":" else (visible_w + 2)
    image = Image.new("L", (width, HEIGHT), 0)
    draw = ImageDraw.Draw(image)
    x = (width - visible_w) // 2 - bbox[0]
    y = (HEIGHT - (bbox[3] - bbox[1])) // 2 - bbox[1]
    draw.text((x, y), char, font=font, fill=255)

    levels = [min(3, (value + 42) // 85) for value in image.getdata()]
    packed = bytearray()
    for pos in range(0, len(levels), 4):
        values = levels[pos:pos + 4]
        values += [0] * (4 - len(values))
        packed.append((values[0] << 6) | (values[1] << 4) | (values[2] << 2) | values[3])
    glyphs.append((char, width, bytes(packed)))

offsets: list[int] = []
bitmap = bytearray()
for _, _, packed in glyphs:
    offsets.append(len(bitmap))
    bitmap.extend(packed)

lines = [
    "#pragma once",
    "#include <Arduino.h>",
    "",
    "// Generated by tools/generate_clock_digits.py from Google Fonts Roboto Condensed.",
    f"static constexpr uint8_t CLOCK_DIGIT_HEIGHT = {HEIGHT};",
    f"static constexpr uint8_t CLOCK_DIGIT_COUNT = {len(CHARS)};",
    f'static constexpr char CLOCK_DIGIT_CHARS[] = "{CHARS}";',
    "static const uint16_t CLOCK_DIGIT_OFFSETS[] PROGMEM = {",
    "  " + ", ".join(map(str, offsets)),
    "};",
    "static const uint8_t CLOCK_DIGIT_WIDTHS[] PROGMEM = {",
    "  " + ", ".join(str(width) for _, width, _ in glyphs),
    "};",
    "static const uint8_t CLOCK_DIGIT_BITMAP[] PROGMEM = {",
]
for pos in range(0, len(bitmap), 16):
    lines.append("  " + ", ".join(f"0x{value:02X}" for value in bitmap[pos:pos + 16]) + ",")
lines.extend(["};", ""])
OUT_PATH.write_text("\n".join(lines))
print(f"{OUT_PATH}: {len(bitmap)} packed bytes")
