#!/usr/bin/env node

import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

const input = resolve(process.argv[2] || 'assets/clock/bunny-dance.gif');
const output = resolve(process.argv[3] || 'src/features/clock/BunnyAnimation.h');
const width = 62;
const height = 58;
const frameMs = 100;
const work = mkdtempSync(join(tmpdir(), 'geektv-bunny-'));
const rawPath = join(work, 'frames.rgb');

try {
  // The prepared monochrome source is 102x89. Its actual animation occupies
  // x=9..93 and y=0..79; crop that content before scaling it into the footer.
  execFileSync('ffmpeg', [
    '-hide_banner', '-loglevel', 'error',
    '-i', input,
    '-vf', `crop=85:80:9:0,scale=${width}:${height}:flags=lanczos`,
    '-f', 'rawvideo', '-pix_fmt', 'rgb24', rawPath,
  ]);

  const rgb = readFileSync(rawPath);
  const rgbFrameBytes = width * height * 3;
  if (rgb.length % rgbFrameBytes !== 0) {
    throw new Error(`Unexpected raw frame size: ${rgb.length}`);
  }

  const frameCount = rgb.length / rgbFrameBytes;
  const packedFrameBytes = Math.ceil(width * height / 4);
  const packed = Buffer.alloc(frameCount * packedFrameBytes);

  for (let frame = 0; frame < frameCount; frame++) {
    const rgbBase = frame * rgbFrameBytes;
    const packedBase = frame * packedFrameBytes;
    for (let pixel = 0; pixel < width * height; pixel++) {
      const i = rgbBase + pixel * 3;
      const luminance = Math.round(
        rgb[i] * 0.2126 + rgb[i + 1] * 0.7152 + rgb[i + 2] * 0.0722,
      );
      // The prepared source is already inverted: black becomes transparent
      // and the white/gray character keeps four brightness levels.
      const level = Math.max(0, Math.min(3, Math.round(luminance / 85)));
      const byteIndex = packedBase + Math.floor(pixel / 4);
      packed[byteIndex] |= level << (6 - (pixel % 4) * 2);
    }
  }

  const rows = [];
  for (let i = 0; i < packed.length; i += 16) {
    rows.push(`  ${Array.from(packed.subarray(i, i + 16), value =>
      `0x${value.toString(16).padStart(2, '0')}`).join(', ')},`);
  }

  const header = `// Generated by tools/generate_bunny_animation.mjs.
// Source: assets/clock/bunny-dance.gif
#pragma once
#include <Arduino.h>

static constexpr uint8_t BUNNY_WIDTH = ${width};
static constexpr uint8_t BUNNY_HEIGHT = ${height};
static constexpr uint8_t BUNNY_FRAME_COUNT = ${frameCount};
static constexpr uint16_t BUNNY_FRAME_MS = ${frameMs};
static constexpr uint16_t BUNNY_FRAME_BYTES = ${packedFrameBytes};

static const uint8_t BUNNY_FRAMES[] PROGMEM = {
${rows.join('\n')}
};
`;
  writeFileSync(output, header);
  console.log(`Generated ${frameCount} frames, ${packed.length} packed bytes`);
} finally {
  rmSync(work, { recursive: true, force: true });
}
