#!/usr/bin/env python3
"""Generate a compact 4-bit antialiased time-only glyph atlas."""

from pathlib import Path
import sys

from PIL import Image, ImageDraw, ImageFont


FONT_PATH = Path(sys.argv[1] if len(sys.argv) > 1 else "assets/fonts/Montserrat-VariableFont_wght.ttf")
OUTPUT = Path(sys.argv[2] if len(sys.argv) > 2 else "src/features/clock/SmoothTimeFont.h")
GLYPHS = "0123456789:"
HEIGHT = 70
DIGIT_WIDTH = 44
COLON_WIDTH = 18
FONT_SIZE = 66


font = ImageFont.truetype(str(FONT_PATH), FONT_SIZE)
try:
    font.set_variation_by_name("Bold")
except (AttributeError, OSError):
    pass

packed = bytearray()
offsets = []
widths = []

for glyph in GLYPHS:
    width = COLON_WIDTH if glyph == ":" else DIGIT_WIDTH
    image = Image.new("L", (width, HEIGHT), 0)
    draw = ImageDraw.Draw(image)
    box = draw.textbbox((0, 0), glyph, font=font)
    glyph_width = box[2] - box[0]
    glyph_height = box[3] - box[1]
    x = round((width - glyph_width) / 2 - box[0])
    y = round((HEIGHT - glyph_height) / 2 - box[1])
    draw.text((x, y), glyph, fill=255, font=font)

    offsets.append(len(packed))
    widths.append(width)
    pixels = list(image.getdata())
    for i in range(0, len(pixels), 2):
        hi = min(15, max(0, round(pixels[i] / 17)))
        lo = min(15, max(0, round(pixels[i + 1] / 17))) if i + 1 < len(pixels) else 0
        packed.append((hi << 4) | lo)

rows = []
for i in range(0, len(packed), 16):
    rows.append("  " + ", ".join(f"0x{value:02x}" for value in packed[i:i + 16]) + ",")

OUTPUT.write_text(
    f"""// Generated by tools/generate_smooth_time_font.py.
// Font: Montserrat Bold (SIL Open Font License 1.1)
#pragma once
#include <Arduino.h>

static constexpr uint8_t SMOOTH_TIME_HEIGHT = {HEIGHT};
static constexpr uint8_t SMOOTH_TIME_GLYPH_COUNT = {len(GLYPHS)};
static const char SMOOTH_TIME_CHARS[] = "{GLYPHS}";
static const uint16_t SMOOTH_TIME_OFFSETS[] PROGMEM = {{
  {", ".join(map(str, offsets))}
}};
static const uint8_t SMOOTH_TIME_WIDTHS[] PROGMEM = {{
  {", ".join(map(str, widths))}
}};
static const uint8_t SMOOTH_TIME_BITMAP[] PROGMEM = {{
{chr(10).join(rows)}
}};
""",
    encoding="utf-8",
)

print(f"Generated {len(GLYPHS)} glyphs, {len(packed)} packed bytes")
